"""create projects and pages tables

Revision ID: db350d651ed0
Revises: 
Create Date: 2026-07-17 21:25:40.710156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db350d651ed0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seeded verbatim from frontend/src/lib/mockData.ts (MOCK_ABOUT /
# MOCK_AI_WORKFLOW) — the AI Workflow copy is locked per SPEC.md §4 and
# must not be paraphrased; the About body is the same placeholder the
# frontend already shows, pending the TUI writing a real bio.
ABOUT_CONTENT = {
    "body": "Placeholder About copy — pending final bio.",
    "linkedinUrl": "#",
    "devpostUrl": "#",
}

AI_WORKFLOW_CONTENT = {
    "title": "Personal AI Workflow: Noctis",
    "intro": (
        "I got tired of re-teaching Claude the same process every project, and "
        "losing track of which markdown file was actually current across a "
        "dozen repos. So I built a system instead of repeating myself."
    ),
    "blocks": [
        {
            "heading": "The second brain.",
            "body": (
                "An Obsidian vault, following Andrej Karpathy's pattern for "
                "LLM-maintained wikis — Claude re-reads and updates existing "
                "pages as new material lands, so it compounds instead of just "
                "growing. If it won't still be true in three months, it "
                "doesn't earn a page."
            ),
        },
        {
            "heading": "Claude Code ↔ Claude Desktop continuity.",
            "body": (
                "One process file, read live by both — no pasting the same "
                "rules into two places and watching them drift."
            ),
        },
        {
            "heading": "The build spine.",
            "body": (
                "Spec signed off before code, tasks kept small, every "
                "unstated assumption surfaced before implementation, a "
                "critic subagent that can flag correctness problems but "
                "can't fix them — so it can't rubber-stamp its own work — "
                "and an eight-step ship gate that stops at the first "
                "failure."
            ),
        },
        {
            "heading": "The connectors.",
            "body": (
                "An MCP connector (istefox) bridges Claude straight into "
                "the Obsidian vault as real tool calls mid-conversation — "
                "not something I copy-paste between windows. Planning and "
                "the knowledge base stay one system, not two I sync by "
                "hand."
            ),
        },
        {
            "heading": "Design before wiring.",
            "body": (
                "Screens get built against fake data first. Only once "
                "that's approved does the UI's data shape become the "
                "actual backend contract — never the other way round, so "
                "a rough first draft never quietly calcifies into the "
                "API."
            ),
        },
        {
            "heading": "The maintenance loop.",
            "body": (
                "Not one-and-done — the whole setup gets periodically "
                "re-audited against how I actually work, not left to rot "
                "as a document nobody revisits."
            ),
        },
        {
            "heading": "How a project moves.",
            "body": (
                "Spec approved in the vault → built task by task against "
                "the spine → cleared through all eight ship-gate steps → "
                "decisions filed back into the second brain, so the next "
                "project starts a step ahead."
            ),
        },
    ],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('writeup', sa.Text(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('github_stars', sa.Integer(), nullable=False),
    sa.Column('github_language', sa.String(), nullable=True),
    sa.Column('github_last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo_media_type', sa.String(), nullable=False),
    sa.Column('demo_media_url', sa.String(), nullable=False),
    sa.Column('video_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    # ### end Alembic commands ###

    pages_table = sa.table(
        "pages",
        sa.column("key", sa.String),
        sa.column("content", postgresql.JSONB),
    )
    op.bulk_insert(
        pages_table,
        [
            {"key": "about", "content": ABOUT_CONTENT},
            {"key": "ai_workflow", "content": AI_WORKFLOW_CONTENT},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('pages')
    # ### end Alembic commands ###
